version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: play.lister
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: songs 
  app:
    build: .
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_NAME: songs
      MONGO_USER: play.lister
      MONGO_PASS: 123
      SECRET: 9b9bed51-fddd-424f-8f4a-fcc77593604f
    ports:
      - 3030:3030
    volumes: 
      - .:/usr/app
    links:
      - mongo
    depends_on:
      - mongo